---
issues:
  exclude-use-default: false

linters:
  enable:
  - bodyclose
  - gocognit
  - gocyclo
  - goimports
  - golint
  - gosec
  - lll
  - prealloc
  - unconvert
  - unparam
  - whitespace
  - wsl

# vim: ts=2 sw=2 et
