---
issues:
  exclude-use-default: false

linters:
  disable:
  - funlen
  - gochecknoglobals
  - gochecknoinits
  - godox
  - gomnd
  - nestif
  - testpackage
  enable-all: true

# vim: ts=2 sw=2 et
